<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>DivineDiurganate</AssemblyName>
    <RootNamespace>DivineDiurganate</RootNamespace>
    <LangVersion>11.0</LangVersion>
    <Deterministic>true</Deterministic>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <OutputPath>..\..\1.6\1.6\Assemblies\</OutputPath>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <OutputPath>..\..\1.6\1.6\Assemblies\</OutputPath>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4633" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="0Harmony">
      <HintPath>Libs\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AlienRace">
      <HintPath>Libs\AlienRace.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FacialAnimation">
      <HintPath>Libs\FacialAnimation.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Flyover\AbilitySpawnFlyOver\CompAbilityEffect_SpawnFlyOver.cs" />
    <Compile Remove="Flyover\AbilitySpawnFlyOver\CompProperties_AbilitySpawnFlyOver.cs" />
    <Compile Remove="Flyover\AircraftHangar\CompAbilityEffect_AircraftStrike.cs" />
    <Compile Remove="Flyover\AircraftHangar\CompAircraftHangar.cs" />
    <Compile Remove="Flyover\AircraftHangar\WorldComponent_AircraftManager.cs" />
    <Compile Remove="Flyover\BlockedByFlyOverFacility\CompAbilityEffect_BlockedByFlyOverFacility.cs" />
    <Compile Remove="Flyover\DestroyFlyOverByFacilities\CompProperties_DestroyFlyOverByFacilities.cs" />
    <Compile Remove="Flyover\FlyOverDropPod\CompProperties_FlyOverDropPod.cs" />
    <Compile Remove="Flyover\FlyOverEscort\CompFlyOverEscort.cs" />
    <Compile Remove="Flyover\FlyOverEscort\CompProperties_FlyOverEscort.cs" />
    <Compile Remove="Flyover\FlyOverFacilities\CompAbilityEffect_RequireFlyOverFacility.cs" />
    <Compile Remove="Flyover\FlyOverFacilities\CompFlyOverFacilities.cs" />
    <Compile Remove="Flyover\GlobalFlyOverCooldown\CompAbilityEffect_GlobalFlyOverCooldown.cs" />
    <Compile Remove="Flyover\GlobalFlyOverCooldown\CompFlyOverCooldown.cs" />
    <Compile Remove="Flyover\GroundStrafing\CompGroundStrafing.cs" />
    <Compile Remove="Flyover\SectorSurveillance\CompSectorSurveillance.cs" />
    <Compile Remove="Flyover\SendLetterAfterTicks\CompProperties_SendLetterAfterTicks.cs" />
    <Compile Remove="Flyover\SendLetterAfterTicks\CompSendLetterAfterTicks.cs" />
    <Compile Remove="Flyover\ShipArtillery\CompProperties_ShipArtillery.cs" />
    <Compile Remove="Flyover\ShipArtillery\CompShipArtillery.cs" />
    <Compile Remove="Pawn_Comps\MechArmor\CompMechArmor.cs" />
    <Compile Remove="Ritual\RitualBehaviorWorker_ExorcistSpeech.cs" />
  </ItemGroup>
</Project>
